### PR TITLE
Added checks for L6364 hw fault

### PR DESCRIPTION
**Pull request by Lmariotti95**
Added a timeout for R/W operations with L6364 cause infinite loops scares af

### CODE REVIEW

**Comment by TiNredmc** [comment]
Hi Lorenzo,

I've tested your code and it seems to work just fine with optimization flag set. I haven't inject SPI fault to test it yet though. But I think I'm ready to merge the code but there are some few error here and there to correct first.

In the ```spi.c```, I believe that you forgot the comma after the ```uint8_t *statusReg``` of the fast read and write function.
Also in the fast write function line 456-457, the count check should return 0 when count is equal to zero (all byte are written).

As for the millis() function. Could you kindly include the systick header inside the spi.h instead of spi.c.

Thanks!

**Comment by Lmariotti95** [comment]
Sorry about syntax error, not able to build at this point. As soon as possible I'll try to fix that issue.
Anyway why do you include a file in a header if the latter does not need it? Increasing unused visibility it's usually a bad practice, can you explain your idea please?

**Comment by TiNredmc** [comment]
Hi Lorenzo,

As for why I included other header inside the .h file, It's more tidy to put it there so the source file only need to include just one header.

**Comment by Lmariotti95** [comment]
That's "nicer to see" from the source file view but also causes that many resources are included in files that doesn't require them. But for sure I can follow those guideline, mine was just an advice

**Comment by TiNredmc** [comment]
Code merged, Thanks for the contribution!

**Pull request merged**
